"""empty message

Revision ID: 7722e3399149
Revises: 
Create Date: 2018-02-25 18:47:20.766447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7722e3399149'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size_key_shirt_casual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_short', sa.Text(length=6), nullable=True),
    sa.Column('size_long', sa.Text(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('size_long'),
    sa.UniqueConstraint('size_short')
    )
    op.create_table('size_key_shirt_dress_neck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('size_key_shirt_dress_sleeve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('link_user_size_shirt_casual',
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['size_id'], ['size_key_shirt_casual.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('size_id', 'user_id')
    )
    op.create_table('link_user_size_shirt_dress_neck',
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['size_id'], ['size_key_shirt_dress_neck.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('size_id', 'user_id')
    )
    op.create_table('link_user_size_shirt_dress_sleeve',
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['size_id'], ['size_key_shirt_dress_sleeve.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('size_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_user_size_shirt_dress_sleeve')
    op.drop_table('link_user_size_shirt_dress_neck')
    op.drop_table('link_user_size_shirt_casual')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('size_key_shirt_dress_sleeve')
    op.drop_table('size_key_shirt_dress_neck')
    op.drop_table('size_key_shirt_casual')
    # ### end Alembic commands ###
